apiVersion: api.my.domain/v1alpha1
kind: Migration
metadata:
  name: migration-sample
  labels:
    example-webhook-enabled: "true"
  namespace: practice-system
spec:
  # TODO(user): Add fields here
  podname: checkpoint-redis5
  deployment: 
  namespace: migration
  destinationNode: workernode01
  # an array of strings representing the names of pods to migrate
  destinationNamespace: migration
  # if the name listed in specify exists in pod name, then the pod will be migrated
  specify: 
    # - nginx2
    # - redis2 

  # helm: 
  #   - name: nginx
  #     chart: stable/nginx
  #     version: 1.0.0

  # Optional field: deployment
  # Users can choose to include it or leave it empty
  # deployment: 

  
